### ISSUE TITLE
Looking for new maintainer(s)

### ISSUE THREAD

**Issue by Nick-Lucas** [Stratajet/UnitConversion#16]
@rohitjha  @gkampolis @anovik @agdenadel 

Hi everyone,

Apologies for having not responded to your PRs and interest in the project. 

Because of priorities at Stratajet and this not being a heavily used package for us, I've not been able to maintain it like I maintain some of my other OSS packages. I would love for UnitConversion to continue to exist if you're all getting value in it, but just can't commit the time myself. 

This in mind, would anyone be interested in taking over as maintainer? Either reply here or throw me an [email](mailto:nlucas@stratajet.com) if so, and we can talk about a handover of things like the nuget repo.

Nick

**Comment by gkampolis** [comment]
I'm going to have some time on my hands for the second half of December and after New Year's, so maybe we could arrange something (I was planning to add density units anyway and who knows what else). 

However this would be the first time I'd become a maintainer for an existing project, so some guidance on the procedures involved would be greatly appreciated!

Kind regards,

George

**Comment by Nick-Lucas** [comment]
Great! I'm happy to walk you through some bits.

It's all quite straight-forward though. You just need to set up a free AppVeyor account and create a project for your fork of the repo. Most of the configuration is in the repo, so it's just some security stuff like the key for deploying to Nuget.

**Comment by gkampolis** [comment]
@Nick-Lucas I finally have something resembling free time. Can we start the process so when I actually get more time around start of  February, I can spend it contributing to this repo? 😄

**Comment by Nick-Lucas** [comment]
Hi @gkampolis 

You just need to go through a few steps:

* Fork this repo, and submit a PR on the readme here, to point users at the new repo. I'll hit merge for you
* Let me know your nuget username, make an account if you need to, and I will transfer the nuget package to you
* Set up a free appveyor account, then connect it to your github repo and the nuget repo. There's a bit of learning to do here, but 98% of the configuration is in this repo's yaml file, so you just need to sort out auth

Let me know if you have any questions.

**Comment by gkampolis** [comment]
Hi @Nick-Lucas 

- I've made the change to the readme file, however the change is bundled with the introductions of volume units I did in the earlier pull request. Do you need me to revert those commits (and re-apply them later)? Please note that there are no conflicts and the check with appveyor is passed.

- My nuget profile can be found here: [gkampolis](https://www.nuget.org/profiles/gkampolis).

- I've created an appveyor account and a new project therein, I've pointed it to my fork of UnitConversion and to the appveyor.yaml that was already available. I've hit the build button, everything seems ok. Not sure what I need to do with authorship and which are my next steps.

Cheers!

**Comment by Nick-Lucas** [comment]
* don't worry I'll just merge it. It's your codebase now anyway ;)
* I've added you on nuget, once you've accepted you should be able to remove the stratajet account on your end
* You can set up a deployment target pointing at the nuget repo once you have ownership, and it sounds like you've done the hard part. I never set anything clever up like auto-releasing on git version tags, so you just have to go in to a build and hit deploy once you've incremented the version number in the csproj.

**Comment by anovik** [comment]
Hi @Nick-Lucas  @gkampolis 

May I ask you about the status of other PRs made to Stratajet? Will they be merged to new repo?

Thanks.

**Comment by gkampolis** [comment]
@anovik 
I'm going through the process of writing a `contribution.md` and some style cop basic rules to settle on variable naming (PascalCase etc.), everything should be done sometime next week, depending on available time.

You should be making all pull requests "against" my repo of the project, [here](https://github.com/gkampolis/UnitConversion).

**Comment by gkampolis** [comment]
@anovik If you're so inclined, I've set up a gitter chatroom. We can talk further about moving your pull requests over there. 

Of course, everyone is more than welcome to join in and participate.

[![Gitter chat](https://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg)](https://gitter.im/UnitConversionCSharp)

**Comment by gkampolis** [comment]
@Nick-Lucas hi there, I've pretty much set up everything up and all is going well.

However I noticed that my repo is still listed as a fork and not the "home" of the project. 
![capture](https://user-images.githubusercontent.com/6932775/36026432-f987455e-0d8e-11e8-946e-bfba919ed254.PNG)

I thought that you may want to transfer this repo to me, this would solve the problem posited by @anovik as the pull requests to Stratajet's repo would be now handled by me, ensuring continuity instead of forcing everyone to migrate to the new location. 

If you agree to this, I'll create a new pull request with the changes I've doe so far and then you can transfer this repo to me (in the repo's settings).

Your thoughts?

**Comment by Nick-Lucas** [comment]
Looks like I can't directly transfer it to you, but have made you an admin for it.

With Admin rights you can likely resolve this, as I believe you can transfer out of the organisation to your own account.

I do suggest you transfer it out of Stratajet, as I no longer work for the company and no-one is supporting this project.

Let me know if I can do anything else

**Comment by gkampolis** [comment]
@Nick-Lucas That worked! Thanks for being so prompt! 👍
