### ISSUE TITLE
StyleCop doesn't seem to recognize parameters in sln.dotsettings

### ISSUE THREAD

**Issue by gkampolis** [Stratajet/UnitConversion#18]
# Issue short description
As the title. Example picture:
![inkedcapture_li](https://user-images.githubusercontent.com/6932775/36067830-f63725e2-0ebd-11e8-9f34-c492d2f6f330.jpg)

## Expected Behavior
By adding "exceptions" to UnitConversion.sln.dotsettings StyleCop shouldn't show warnings for that specified issue.
## Actual Behavior
Issues are still displayed.
## Steps to Reproduce
By cloning the [UnitConversion repo](https://github.com/gkampolis/UnitConversion), this should be reproducible (or it's a problem in my settings somewhere).
## Technical Details (OS, project version, relevant details)
* Visual Studio Community 2017 15.5.5 (latest version)
* StyleCop as [Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop) Version: 5.0.6419.0 (latest)
* Windows 10

**Comment by prasadtelkikar** [comment]
To fix this issue I follewed some steps, that are as follows

1. Install [Style cop](https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop) plugin for Visual studio.
2. Start your visual studio.
3. Right click on project and select StyleCop Settings option from it.

![image](https://user-images.githubusercontent.com/10395798/49990125-9090e580-ffa2-11e8-9161-e10be4b4690d.png)

4. Now untick rules which you want to skip in the warning tab.

![image](https://user-images.githubusercontent.com/10395798/49990214-d6e64480-ffa2-11e8-8ca3-8a6175c0e18d.png)

This will generate _Settings.StyleCop_ file in project, which will suppress warnings from project
