### ISSUE TITLE
New maintainer(s) needed

### ISSUE THREAD

**Issue by gkampolis** [Stratajet/UnitConversion#22]
Hi everyone,

Unfortunately I find myself without free time to improve upon the code base left by @Nick-Lucas while also moving towards different approaches and technologies (I'm primarily focusing on R).

Therefore, I cannot continue to actively maintain the project and I'm looking for anyone interested to take over. Let me know if you're interested and we can go through the handover of the project, incl. the nuget repo.

cc: @rohitjha @MarkusKgit @anovik @prasadtelkikar @akritikos @Nick-Lucas

**Comment by rohitjha** [comment]
Hi @gkampolis, I am interested in helping maintain the repo and improve the code base.

**Comment by prasadtelkikar** [comment]
Hi Rohit,

I can help you in maintaining this repo and providing good open source
project to this community

Thanks,
Prasad

**Comment by MarkusKgit** [comment]
Hi,

I would like to help with code contributions, reviews etc. but I don't have the time for full ownership.

Greetings,
Markus

**Comment by anovik** [comment]
Hi,

I can also help with code contributions but I don't have enough time right now to maintain the repo.

Best regards,
Anna.

**Comment by gkampolis** [comment]
Hi @rohitjha, glad to see you're interested.

As you can see in the previous thread [here](https://github.com/gkampolis/UnitConversion/issues/16) the process involves 3 elements:

1. I'll see if I can transfer the repo directly to you. If not, I'll give you admin rights (and then you can transfer it on your own).
2. You'll need to set up a free AppVeyor account if you don't have one already (and create an AppVeyor project for the repo)
3. You'll need to ceate a nuget account, if you don't have one already, so I can transfer the ownership to you

The instructions for building the project are already present in appveyor.yaml and you should be able to get it going from the get go, by applying your own AppVeyor id key. The propagation to nuget is fairly simple, after you're happy with the state of the project for a new release, you simply need to increase the version prefix in the csproj and commit, triggering a new build by AppVeyor, which will "see" the new version and send that to nuget. Of course, you can move to a more sophisticated way of doing things using git tags, but I have no idea how to do this.

Let me know when you want to initiate all this. :)

Finally, I wish to thank everyone for their enthusiasm for code contributions to help the project stay alive.

**Comment by gkampolis** [comment]
@rohitjha I've tried to transfer ownership to you but I get the error message `rohitjha/UnitConversion already exists`.

Can you rename your fork or simply rename your local folder (to keep a backup of your work so far) so I can continue with the transfer?

**Comment by rohitjha** [comment]
@gkampolis I've renamed my fork to `UnitConversionOld` so you should be able to transfer now. Also, I've created a free AppVeyor account and a NuGet account (username `rohitjha`).

**Comment by gkampolis** [comment]
@rohitjha for some reason it still pops an error: `rohitjha already has a repository in the gkampolis/UnitConversion network`, I assume due to it being a fork from the original.

When I assumed maintenance of the project originally, I simply copied the project locally on my own machine and then deleted my fork of the project from GitHub. Of course, you may find other options but I don't know any other way.

Regarding the nuget package, I tried adding you as an owner to the project, but nuget complains that you haven't verified your email address yet.

**Comment by gkampolis** [comment]
@rohitjha are you still interested in taking up the project?

**Comment by atulmish** [comment]
I am interested in taking up this project

**Comment by prasadtelkikar** [comment]
@gkampolis @rohitjha , lot of people are interested to take up this project, still no one started actual work on it.
My question to you is, when we are going to start working on this project? 
what is next plan?

**Comment by gkampolis** [comment]
Sorry for the delay everyone, I never heard back from @rohitjha (almost a month ago) and then my own outside commitments kicked in.

@atulmish Many thanks for your interest, I'm very grateful you're willing to step in. I'll try transferring the repo to you directly, later on tonight. For this to succeed, you must not have already a repo with the same name or even a fork of this one (see previous attempt with @rohitjha above).

If you already have work you'd like to commit, you can either create a pull request that I'll accept  (and then you should delete your repo), or save your work locally (and then delete your repo) and commit afterwards.

@prasadtelkikar Apart from @rohitjha and @atulmish, everyone else said that they're willing to contribute but not take over the project. So not a lot of people but just two, with the first one going silent 1.5 months ago and @atulmish kindly expressing his interest 6 days ago. If you wanted to take over, I would have gladly transferred the repo to you, had you indicated that you were available and willing.

**Comment by prasadtelkikar** [comment]
@gkampolis , I am ready to take ownership of this repo, as I have no experience in open source maintenance so I did not raise my hands for the same.
If no one is taking this role, then I am ready to take this challenge. Just need your help and guidance for maintaining this repo.

Note: I deleted this repo from my account; so you can proceed with the transferring steps without errors

**Comment by atulmish** [comment]
Hi @gkampolis,

I am glad to hear back from you and really grateful that you are willing to transfer the ownership to me.

The following is the plan for the next quarter.

Phase 0: Takeover Ownership
Resolve open issues.

Phase I: New types of converters 

Power Converter
Atmospheres Converter
Energy Converter
Temperature Converter

Phase II: Developer Experience and Usability Enhancements

Extension
Fluent Interface
Async Support
Documentation Enhancement

Phase III: Plugable third parties
Currency Converter (Plugin third-party provider)
More to come

I will also welcome new contributors and set up a plan accordingly with the interested contributors including @prasadtelkikar and others. I think it will be a good opportunity for everyone interested to collaborate and support the project under the guidance and gain experience.

I look forward to the transfer of this repository.

Thanks,
Atul

**Comment by gkampolis** [comment]
@atulmish I've initiated the transfer, you should receive a request soon! Delighted that you seem to have the required time and vision to take this project further.

@prasadtelkikar I'm sorry then, maybe I misunderstood. Hopefully a collaborative spirit will prevail and be fostered. Looking forward to you been part of the kernel of an active community around the project.

**Comment by atulmish** [comment]
I am happy to confirm that I have accepted the transfer. 

@gkampolis we would also need the ownership of AppVeyor and Nuget.

**Comment by gkampolis** [comment]
@atulmish I've sent you the relevant request over at nuget. That should pretty much be everything I think.

You'll need to link the github repo to an AppVeyor project which will update the nuget deployment once you manually change the version of the package. See previous comments on this thread and let me know if anything is amiss.

:)

**Comment by atulmish** [comment]
The ownership transfer is complete so I am closing this issue.
