### ISSUE TITLE
Temperature: Celsius to Kelvin issue

### ISSUE THREAD

**Issue by anovik** [Stratajet/UnitConversion#23]
It is assumed in TemperatureHelper.cs and in tests that:

[°C] = [K] − 273

But actually 

[°C] = [K] − 273.15 

Need to fix that, this 0.15 is small but quite important for physics field, for instance.

https://en.wikipedia.org/wiki/Kelvin

**Comment by gkampolis** [comment]
Good catch! At the moment I'm keeping the code "frozen" until a new maintainer is onboard.

Are you willing to submit a PR on this?

**Comment by anovik** [comment]
I can do this but I think it's better to wait until the new maintainer will be finally here.

**Comment by gkampolis** [comment]
Thanks @anovik, good call I think.
