### ISSUE TITLE
Find way to correct for float errors

### ISSUE THREAD

**Issue by Nick-Lucas** [Stratajet/UnitConversion#8]
Most conversion works perfectly, but due to floating point precision, it's possible that conversions may fail if enough floating point error accrues.

An example of this can be found [here](https://github.com/Stratajet/UnitConversion/blob/master/UnitConversionTests/TimeConverterTests.cs#L124) where without rounding to 8-decimal places, the value comes back as very slightly off.

Some research needed.

**Comment by prasadtelkikar** [comment]
@Nick-Lucas, @gkampolis I Fixed this issue using extension method which compares calculated value with epsilon.(A lowerbound and upper bound value)
Changes are ready, once PR which is in the queue get added I will merge changes for this issue.
Code fix looks like

```
public static class ExtensionMethods
    {
        public const double lowerBoundEpsilon = 0.99999;
        public const double upperBoundEpsilon = 0.999999999;

        /// <summary>
        /// Return close enough value
        /// </summary>
        /// <param name="value">result value to be check</param>
        /// <returns>Closed value</returns>
        public static double CheckCloseEnoughValue(this double value)
        {
            double diff = value - Math.Floor(value);
            if (diff > lowerBoundEpsilon && diff < upperBoundEpsilon)
                return Math.Ceiling(value);
            return value;
        }
  }
```
We can change upper bound and lower bound  values as per our need. I found this approach more elegant. Suggestions are welcome.
Reference: Stackoverflow: [How do I find if two variables are approximately equals?](https://stackoverflow.com/questions/3420812/how-do-i-find-if-two-variables-are-approximately-equals)
Article: [Comparing floating point numbers](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/)
